### PR TITLE
Moved flows from score-language

### PR DESCRIPTION
**Pull request by TudorLesanHP**
@oritstone could you please review this?

### CODE REVIEW

**Comment by oritstone** [comment]
Nice work @TudorLesanHP.
Did you use the CLI to check that the flows & operations still work?

A few comments:
- In *less_than_percentage* operation: 
  - Missing documentation for all the inputs\outputs\results. Make sure  you document also what is the required format (for example get a string including the %). 
  - I would keep the convention of multiple words in small letters separated by _ also for the outputs
- In *subtract_sets*:
  - Missing documentation for all the inputs\outputs\results.
  - it seems to me that there is no FAILURE result - it will never get to failure.
  - I didn't quite understand from the documentation what does the operation does. It subtract from each number in the set the matching number in the other set?
- In *string_occurrence_counter* - missing documentation for the outputs
- In *demo_dev_ops* flow 
  - I would better explain what the flow does
  - I don't see any outputs in the flow, but there is in the comment :)
- In *stop_container*: Input *containerID* is not optional and does not have a default in the flow
- Maybe it is better to change the name of the dir: *health-checks* to simply *health*
- In *diskspace_health_check*: 
  - I would better explain what the flow does
  - I don't see any outputs in the flow, but there is in the comment :)
- In *get_all_images*:
  - *command*, *arguments*, *characterSet*, *pty* inputs are missing from the comment
  -  missing documentation on the format of *imageList* output
- In *get_used_images*: missing documentation on the format of *imageList* output
- In *get_used_images_flow*: 
  - missing documentation on the format of *used_images_list* output
  - missing documentation on possible results
- In *validate_linux_machine_ssh_access*
  - missing indentation for the inputs attributes (default, required...)
- In *extract_servers*
  - missing documentation for outputs *returnResult* & *returnCode*
  - There is nice explanation on when we get to each result of the flow, but we don't have the code in the flow...
- In *get_server_id*:
  - missing documentation for outputs *returnResult* & *returnCode*
  - There is nice explanation on when we get to each result of the flow, but we don't have the code in the flow...
- In *parse_authentication*: 
  - missing documentation for outputs *returnResult* & *returnCode*
  - missing explanation on the other outputs
- In *create_openstack_server*:
  - wrong outputs in the documentation + missing explanation for each one
  - wrong explanation for the results
- In *create_openstack_server_flow*:
  - Explanation on the flow is wrong
  - missing docs on results
- In *delete_openstack_server*: 
  - missing doc on input *headers*
  - missing doc on outputs
- In *get_authentication*: missing doc on outputs
- In *get_openstack_servers*: missing doc on outputs
- In *list_servers*: missing explanation on each output
- In *validate_server_exists*: missing explanation on each output

Once you finish the corrections, please ask SamMarkowitz to review the texts

**Comment by TudorLesanHP** [comment]
@oritstone I tested all the big flows(that use subflows and operations) in the CLI and they still work as intended. Just started working the corrections.

**Comment by meirwah** [comment]
Please review @SamMarkowitz

**Comment by SamMarkowitz** [comment]
Here's what I found in the text portions:

Specific things to fix:
- org/openscore/slang/base/strings/string_occurrence_counter.sl
  - make all "string"s one case: I suggest lowercase
  - container: change to "string in which to search"
  - toFind: change to "string to find"
- org/openscore/slang/docker/containers/demo_dev_ops.sl
  - an error is "sent" instead of "send"
  - insert "to see" to  "tested that" so it reads "tested to see that"
- org/openscore/slang/openstack/create_openstack_server_flow.sl
  - should say "This flow gets"..."and creates" (with "s"s)
- org/openscore/slang/openstack/get_openstack_servers.sl
  - should say "list of OpenStack servers" (with "s")

General comments:
There are some slight inconsistencies throughout. I don't know how important we think these are:
- The usage of blank lines between description, Inputs, etc. I suggest a blank line after the description before the Inputs section. Other sections (Outputs, Results) to follow without a blank line.
- Input and Output descriptions: 
  - should never end with a period.
  - should never begin with the word "the" (just delete it).
  - should not begin with a capital letter unless it is one of the words from the list below.
  - that contain defaults should always look like this "Default:" (capital "D" and ":" at the end).
- Always capitalize (except in variable names obviously)
  - Docker
  - Linux
  - IP
  - SSH
  - ID
  - MySQL
  - OpenStack

**Comment by meirwah** [comment]
SSH op looks good... maybe bind the output returnResult to "ssh_result" ? WDYT?
 
@SamMarkowitz please review fixes to your comments..

**Comment by SamMarkowitz** [comment]
A bit of a long list, but I specified each issue this time.

- org/openscore/slang/base/network/verify_app_is_up.sl
  - capitalize IP in host input
- org/openscore/slang/base/remote_command_execution/ssh/ssh_command.sl
  - capitalize IP in host input
  - change Default value to just Default: in timeout and closeSession inputs
- org/openscore/slang/docker/containers/clear_container.sl
  - capitalize Docker in description 
- org/openscore/slang/docker/containers/create_container.sl
  - capitalize Docker in description and imageID input
- org/openscore/slang/docker/containers/create_db_container.sl
  - capitalize Docker in description
- org/openscore/slang/docker/containers/demo_clear_containers_wrapper.sl
  - capitalize Docker in description
- org/openscore/slang/docker/containers/demo_dev_ops.sl
  - capitalize second Docker in description
  - "The application is then tested to see that it is up" (added "to see")
  - "an error is sent notifying" (chaged "send" to "sent")
- org/openscore/slang/docker/containers/get_container_ip.sl
  - capitalze IP in description
- org/openscore/slang/docker/containers/start_linked_container.sl
  - change two "MySql" to "MySQL" in first two inputs
- org/openscore/slang/docker/containers/stop_container.sl
  - capitalize Docker in description
- org/openscore/slang/docker/images/clear_docker_dangling_images_flow.sl
  - capitalize Docker in description and first output
- org/openscore/slang/docker/images/clear_docker_images.sl
  - capitalize Docker in description and images input
- org/openscore/slang/docker/images/clear_docker_images_flow.sl
  - capitalize Docker in description and two of the outputs
- org/openscore/slang/docker/images/clear_unused_docker_images.sl
  - capitalize Docker in description
- org/openscore/slang/docker/images/get_all_images.sl
  - capitalize Docker in description and the output
- org/openscore/slang/docker/images/get_dangling_images.sl
  - capitalize Docker in description and the output
  - capitalize IDs in the output
- org/openscore/slang/docker/images/get_used_images.sl
  - capitalize Docker in description and the output
  - capitalize IDs in the output
- org/openscore/slang/docker/images/get_used_images_flow.sl
  - capitalize Docker in description
- org/openscore/slang/docker/images/pull_image.sl
  - capitalize Docker in description  
- org/openscore/slang/docker/linux/check_linux_disk_space.sl
  - capitalize Linux in description 
- org/openscore/slang/docker/maintenance/check_mysql_is_up.sl
  - capitalize Docker in container input  
  - capitalize SSH in output
- org/openscore/slang/docker/maintenance/diskspace_health_check.sl
  - capitalize Linux in description
  - remove period from SUCCESS result
- org/openscore/slang/docker/maintenance/docker_images_maintenance.sl
  - capitalize Docker in description
- org/openscore/slang/docker/maintenance/get_mysql_status.sl
  - capitalize Docker in container input 
  - change "number of queries in a second" to "number of queries per second"
  - capitalize SSH in errorMessage output
- org/openscore/slang/docker/maintenance/report_mysql_status.sl
  - capitalize Docker in container input 
- org/openscore/slang/docker/maintenance/retrieve_mysql_status.sl
  - capitalize Docker in container input 
  - change "number of queries in a second" to "number of queries per second"
- org/openscore/slang/openstack/create_openstack_server_flow.sl
  - change description to "This flow gets authentication and creates an OpenStack server." (added "s"s)
  - delete the word "of" from imgRef input
- org/openscore/slang/openstack/get_authentication.sl
  - change to "returnCode is equal to -1" instead of "=" in returnCode output 
- org/openscore/slang/openstack/get_openstack_servers.sl
  - change "server" to "servers" in description
- org/openscore/slang/openstack/openstack_health_check.sl
  - delete word "for" from imgRf input
- org/openscore/slang/openstack/utils/extract_servers.sl
  - change to "builds" instead of "build" in description
- org/openscore/slang/openstack/utils/parse_authentication.sl
  - capitalize ID in first two outputs

**Comment by meirwah** [comment]
why all these "override" used??
just for not documenting them??

**Comment by meirwah** [comment]
not deleting the branch, since we have comments here still relevent!!

**Comment by meirwah** [comment]
@TudorLesanHP please look at comments... you still need to fix these

**Comment by TudorLesanHP** [comment]
@SamMarkowitz @meirwah  just pushed changes to second list of comments. @meirwah I thought we didn't want to offer flexibility to those operations, that's why I put override on every input we didn't use. I can remove it and document all inputs, it's no problem.

**Pull request merged**
