### PR TITLE
added instructions for installing the CLI and running flows

### PR DESCRIPTION
**Pull request by SamMarkowitz**
As per #17. 

Signed-off-by: Sam Markowitz <sam.markowitz@hp.com>

### CODE REVIEW

**Comment by meirwah** [comment]
why not use what i already wrote in slang project ? : https://github.com/openscore/score-language/blob/master/README.md

You are missinghere some stuff , like notice that there is a batch file fort win and for linux it's a diff file...
it look a bit weird to ask the user to go to the website , scroll down, and find the CLI zip...
There should be a download page at least...

**Comment by SamMarkowitz** [comment]
I matched it to what you had in the score-language repo. I'm a little concerned about having to remember to update so many links every time there is a new version of the CLI.

**Comment by meirwah** [comment]
why not have here a link to score-lang doc?

**Comment by SamMarkowitz** [comment]
Do you mean remove the whole thing and replace it with just a link?

**Comment by meirwah** [comment]
@orius123 what you think is better?

**Comment by orius123** [comment]
I think that the docs should have a dedicated section, people don't like navigating between links.. IMHO

**Comment by meirwah** [comment]
we have confilcts here...

**Pull request merged**
