### PR TITLE
added python-lib dir

### PR DESCRIPTION
**Pull request by orius123**
@oritstone / @avimora please review

### CODE REVIEW

**Comment by orius123** [comment]
ping

**Comment by orius123** [comment]
@openscore/developers I want to merge this one but itmoves all of the content files location (create roo directoy called 'content') anyone working in cintent now and mught be affected?

**Comment by meirwah** [comment]
you have the content pull requests open (like #30 ...)

**Comment by oritstone** [comment]
@orius123 is it ready for merge?

**Pull request merged**
