### PR TITLE
Add section on new content validation

### PR DESCRIPTION
**Pull request by oritstone**

### CODE REVIEW

**Comment by oritstone** [comment]
@orius123 @SamMarkowitz please review

**Comment by oritstone** [comment]
Still need to update the link to the latest validator release once it is there
@orius123 is the doc link OK, or do we have to change it also once we revive the site?

**Comment by orius123** [comment]
Don't know.

**Comment by SamMarkowitz** [comment]
I think you should take out the first comma and change the "should" to "must" if we really mean it.

**Comment by oritstone** [comment]
fixes #31

**Pull request merged**
