### PR TITLE
Fixed less_than_percentage.sl results 

### PR DESCRIPTION
**Pull request by tudorlesan**
less_than_percentage.sl was not working anymore. Had to change the result check expressions from result =="true" to result == 1 etc.

### CODE REVIEW

**Comment by orius123** [comment]
I think that just `LESS: reslut` and `MORE: not result` should also work.

**Comment by tudorlesan** [comment]
changed and is working

**Comment by orius123** [comment]
Great. Please submit an issue to change all places that broke after my outputs change.

**Comment by meirwah** [comment]
@tudorlesan please update the branch

**Comment by orius123** [comment]
Please also commit after your changes that we discussed above.

**Comment by tudorlesan** [comment]
I'm putting the changes from this branch to content_result_changes so this branch can be deleted

**Pull request closed without merging**
