### PR TITLE
Add threepar slang flows

### PR DESCRIPTION
**Pull request by remusgolgot**
Create new slang flows that interact with 3Par

### CODE REVIEW

**Comment by meirwah** [comment]
:+1:  but can you add some documantion?

**Comment by remusgolgot** [comment]
Hi Meir,

I've added the documentation for all the slang files in this pull request

**Comment by meirwah** [comment]
:+1: Thanks!!

**Comment by oritstone** [comment]
Developed during the Hackathon. 
It is a great story, but we decided not to merge it

**Pull request closed without merging**
